@startmindmap
* Obsah dokumentu
** Emergentní zdravotní záznam
*** Krevní skupina
*** Alergie a nežádoucí reakce
*** Ostatní emergentní údaje
*** Léčivé přípravky použité při poskytování zdravotních služeb u poskytovatelů lůžkové péče
** Screeningová a preventivní vyšetření
*** Praktický lékař
*** Gynekologie
*** Gastronenterologie
*** Radiologie
*** Laboratoř chemie
*** Pneumologie
*** Urologie
*** Angiologie
@endmindmap