@startmindmap
* Tělo dokumentu
** Screeningová vyšetření
*** Praktický lékař
*** Gynekolog
*** Gastronenterolog
*** Radiolog
*** Laboratoř chemie
*** Pneumolog
*** Urolog
*** Angiolog
** Emergentní zdravotní záznam
*** Krevní skupina
*** Alergie a nežádoucí Reakce
*** Ostatní emergentní údaje
*** Léčivé přípravky použité při poskytování zdravotních služeb u poskytovatelů lůžkové péče
@endmindmap