@startmindmap
* Body
** Screening Examinations
*** General Practitioner
*** Gynecologist
*** Gastroenterologist
*** Radiologist
*** Biochemistry Laboratory
*** Pulmonologist
*** Urologist
*** Angiologist
** Emergency Health Record
*** Blood type
*** Allergies and Adverse Reactions
*** Other emergency data
*** Medication used during healthcare provision at inpatient care providers
@endmindmap
