@startmindmap
* Body
** Emergency Health Record
*** Blood type
*** Allergies and Adverse Reactions
*** Other emergency data
*** Medication used during healthcare provision at inpatient care providers
** Screening and preventive examinations
*** General Practitioner
*** Gynecology
*** Gastroenterology
*** Radiology
*** Biochemistry Laboratory
*** Pulmonology
*** Urology
*** Angiology
@endmindmap
