@startmindmap
* Header
** Identification of the patient/subject
** Patient/subject related contact information
** Health insurance and payment information
** Information recipient
** Author
** Document metadata
** Digital signature
@endmindmap