@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logický model |
| <#TECHNOLOGY>  Profil |
endlegend

class "Emergentní zdravotní záznam" <<LogicalModel>> [[StructureDefinition-LogEmergencyRecordCz.html]]
note top #EEEEAE [[ConceptMap-EmergencyRecord2FHIR-cz.html]]
Concept Mapa
endnote

class "cz-composition-sharedhealthrecord" <<Profile>> [[StructureDefinition-cz-composition-sharedhealthrecord.html]]
class "cz-observation-blood-type" <<Profile>> [[StructureDefinition-cz-observation-blood-type.html]]
class "cz-allergyIntolerance-szz" <<Profile>> [[StructureDefinition-cz-allergyIntolerance-szz.html]]
class "cz-adverse-event" <<Profile>> [[StructureDefinition-cz-adverse-event.html]]
class "cz-MedicationStatement" <<Profile>> [[https://build.fhir.org/ig/HL7-cz/cz-core/StructureDefinition-cz-MedicationStatement.html]]

"Emergentní zdravotní záznam" <|. "cz-composition-sharedhealthrecord"
"Emergentní zdravotní záznam" <|. "cz-observation-blood-type"
"Emergentní zdravotní záznam" <|. "cz-allergyIntolerance-szz"
"Emergentní zdravotní záznam" <|. "cz-adverse-event"
"Emergentní zdravotní záznam" <|. "cz-MedicationStatement"

"cz-composition-sharedhealthrecord" -d[hidden]-> "cz-observation-blood-type"
"cz-observation-blood-type" -d[hidden]-> "cz-allergyIntolerance-szz"
"cz-allergyIntolerance-szz" -d[hidden]-> "cz-adverse-event"
"cz-adverse-event" -d[hidden]-> "cz-MedicationStatement"

@enduml
