Logical: LogEnGynecologyCz
Id: GynecologyCz
Title: "A.3.2 - Gynecology"
Description: """Shared Health Record - Preventive and screening examinations by a gynecologist."""

* colorectalScreening 0..1 Base "A.3.2.1 - Colorectal cancer screening test result" """Result of quantitative fecal occult blood test."""
  * resultDate 0..1 dateTime "A.3.2.1.1 - Date of quantitative FOBT result" """Date on which you evaluate the sample (date on which the FOBT is reported to the health insurance company). Applies to tests evaluated in a doctor's office or laboratory."""
  * resultTOKS 0..1 CodeableConcept "A.3.2.1.2 - Quantitative TOKS result (health service code reported to the health insurance company)" """Health service code reported to the insurance company based on the result of the quantitative TOKS screening."""
  * levelTOKS 0..1 integer "A.3.2.1.3 - TOKS level" """Quantitative immunochemical test value (µg/g)."""
* cytologickeVysetreni 0..1 Base "A.3.2.2 - Result of cytological examination as part of cervical cancer screening" """"""
  * examinationDate 0..1 dateTime "A.3.2.2.1 - Date of cytological examination" """Date of collection of material for cytological examination (cervical smear)."""
  * examinationResult 0..1 CodeableConcept "A.3.2.2.2 - Result of cytological examination" """Result of cytological examination."""
* examinationHPV 0..1 Base "A.3.2.3 - Result of HPV test as part of cervical cancer screening" """"""
  * examinationDate 0..1 dateTime "A.3.2.3.1 - Date of high-risk HPV test" """Date on which material is collected from the patient's cervix."""
  * resultHPV 0..1 CodeableConcept "A.3.2.3.2 - Result of high-risk HPV test" """Result of HPV test."""
* expertColposcopy 0..1 Base "A.3.2.4 - Result of expert colposcopy as part of cervical cancer screening" """"""
  * examinationDate 0..1 dateTime "A.3.2.4.1 - Date of expert colposcopy" """Date on which the patient underwent expert colposcopy."""
  * examinationResult 0..1 CodeableConcept "A.3.2.4.2 - Result of expert colposcopy" """Evaluation of the result of expert colposcopy. The finding is normal and no further intervention is required, or the examination needs to be repeated after a certain interval, or a biopsy is required."""
* preventiveCheckUp 0..1 Base "A.3.2.5 - Result of examination as part of preventive check-up" """"""
  * examinationDate 0..1 dateTime "A.3.2.5.1 - Date of result of preventive check-up" """Date of preventive check-up."""
  * height 0..1 integer "A.3.2.5.2 - Height" """The patient's height in cm."""
  * weight 0..1 integer "A.3.2.5.3 - Weight" """The patient's weight in kg."""
  * vaccinationHPV 0..1 boolean "A.3.2.5.4 - HPV vaccination" """The patient has/has not completed HPV vaccination."""
  * lastHPVVaccinationDate 0..1 date "A.3.2.5.5 - HPV vaccination - year of last dose" """Year when the patient received the last dose of HPV vaccination."""
  * vaccineHPV 0..1 integer "A.3.2.5.6 - HPV vaccination - vaccine" """The vaccine that was administered to the patient."""