Logical: LogCzGynecologyCz
Id: logGynecologyCz
Title: "A.3.2 - Gynekologie"
Description: """Sdílený zdravotní záznam - Preventivní a screeningové vyšetření Gynekologem."""

* kolorektalniScreening 0..1 Base "A.3.2.1 - Výsledek vyšetření v rámci screeningu kolorektálního karcinomu" """Výsledek vyšetření kvantitativního testu okultního krvácení do stolice."""
  * datumVysledku 0..1 dateTime "A.3.2.1.1 - Datum výsledku kvantitativního TOKS" """Datum, kdy provádíte vyhodnocení vzorku (datum vykázání provedeného TOKS zdravotní pojišťovně). Týká se testů vyhodnocených v ordinaci lékaře nebo v laboratoři."""
  * vysledekTOKS 0..1 CodeableConcept "A.3.2.1.2 - Výsledek kvantitativního TOKS (kód zdravotního výkonu vykazovaný zdravotní pojišťovně)" """Kód zdravotního výkonu vykazovaný pojišťovně na základě výsledku screeningového kvantitativního TOKS."""
  * hladinaTOKS 0..1 Quantity "A.3.2.1.3 - Hladina TOKS" """Hodnota kvantitativního imunochemického testu (µg/g)."""
* cytologickeVysetreni 0..1 Base "A.3.2.2 - Výsledek cytologického vyšetření v rámci screeningu karcinomu děložního hrdla" """"""
  * datumVysetreni 0..1 dateTime "A.3.2.2.1 - Datum cytologického vyšetření" """Datum odběru materiálu pro cytologické vyšetření (stěr z děložního hrdla)."""
  * vysledekVysetreni 0..1 CodeableConcept "A.3.2.2.2 - Výsledek cytologického vyšetření" """Výsledek cytologického vyšetření."""
* vysetreniHPV 0..1 Base "A.3.2.3 - Výsledek HPV vyšetření v rámci screeningu karcinomu děložního hrdla" """"""
  * datumVysetreni 0..1 dateTime "A.3.2.3.1 - Datum high risk HPV vyšetření" """Datum, kdy je pacientce proveden odběr materiálu z děložního hrdla."""
  * vysledekHPV 0..1 CodeableConcept "A.3.2.3.2 - Výsledek high risk HPV vyšetření" """Výsledek HPV vyšetření."""
* expertniKolposkopie 0..1 Base "A.3.2.4 - Výsledek expertní kolposkopie v rámci screeningu karcinomu děložního hrdla" """"""
  * datumVysetreni 0..1 dateTime "A.3.2.4.1 - Datum provedení expertní kolposkopie" """Datum, kdy je pacientce provedena expertní kolposkopie."""
  * vysledekVysetreni 0..1 CodeableConcept "A.3.2.4.2 - Výsledek expertní kolposkopie" """Vyhodnocení výsledku expertní kolposkopie. Nález je v normě a není vyžadována další intervence, případně je vyžadováno opakování vyšetření po určitém intervalu, nebo je vyžadováno provedení biopsie."""
* preventivniProhlidka 0..1 Base "A.3.2.5 - Výsledek vyšetření v rámci preventivní prohlídky" """"""
  * datumVysetreni 0..1 dateTime "A.3.2.5.1 - Datum výsledku provedené preventivní prohlídky" """Datum provedení preventivní prohlídky."""
  * vyska 0..1 Quantity "A.3.2.5.2 - Výška" """Výška pacientky v cm."""
  * vaha 0..1 Quantity "A.3.2.5.3 - Váha" """Váha pacientky v kg."""
  * ockovaniHPV 0..1 boolean "A.3.2.5.4 - Očkování HPV" """Pacientka má/nemá dokončené očkovaní proti HPV."""
  * posledniAplikaceOckovaniHPV 0..1 date "A.3.2.5.5 - Očkování HPV - rok aplikace poslední dávky" """Rok, kdy byla pacientce aplikována poslední dávka očkování proti HPV."""
  * ockovaciLatkaHPV 0..1 CodeableConcept "A.3.2.5.6 - Očkování HPV - očkovací látka" """Očkovací látka, která byla pacientce aplikována."""
