Logical: LogEnRadiologyCz
Id: RadiologyCz
Title: "A.3.4 - Radiology"
Description: """Shared Health Record - Screening examination by radiologist."""

* mammographyExamination 0..1 Base "A.3.4.1 - Result of mammography examination as part of breast cancer screening" """"""
  * resultDate 0..1 dateTime "A.3.4.1.1 - Date of mammography examination result" """Date of mammography."""
  * tissueDensity 0..1 CodeableConcept "A.3.4.1.2 - Breast tissue density according to BIRADS/Tabár classification" """Breast tissue density of the patient."""
  * examinationResult 0..1 CodeableConcept "A.3.4.1.3 - Mammography result" """Mammography result."""
* breastBiopsyResult 0..1 Base "A.3.4.2 - Breast cancer screening biopsy result" """"""
  * resultDate 0..1 dateTime "A.3.4.2.1 - Biopsy result date" """Date of biopsy."""
  * biopsyType 0..1 CodeableConcept "A.3.4.2.2 - Biopsy type" """Type of biopsy performed."""
  * biopsyResult 0..1 CodeableConcept "A.3.4.2.3 - Biopsy result" """Result of the biopsy performed."""
* lungExamination 0..1 Base "A.3.4.3 - Result of examination for early detection of lung cancer" """"""
  * resultDate 0..1 dateTime "A.3.4.3.1 - Date of LDCT result" """Date of LDCT"""
  * examinationType 0..1 CodeableConcept "A.3.4.3.2 - Type of LDCT examination" """The patient undergoes an initial examination, a follow-up examination at the scheduled time, or a follow-up examination after an inconclusive result."""
  * examinationResult 0..1 CodeableConcept "A.3.4.3.3 - LDCT result" """LDCT screening result."""
  * recommendedProcedure 0..1 CodeableConcept "A.3.4.3.4 - LDCT examination result: Further recommended examinations" """Final evaluation of results by a physician."""
* prostateExamination 0..1 Base "A.3.4.4 - Prostate cancer early detection examination result" """"""
  * resultDate 0..1 dateTime "A.3.4.4.1 - MRI result date" """Date of MRI"""
  * examinationType 0..1 CodeableConcept "A.3.4.4.2 - Type of MRI examination" """The patient undergoes an MRI without contrast agent or an MRI with contrast agent."""
  * examinationResult 0..1 CodeableConcept "A.3.4.4.3 - MRI result (PI-RADS)" """MRI result according to the PI-RADS system (assessment score)."""
  * PIRADS3Finding 0..1 CodeableConcept "A.3.4.4.4 - Finding in the case of PI-RADS 3" """Zone of finding in the case of PI-RADS 3."""
* examinationAneurysmAbnormalAorta 0..1 Base "A.3.4.5 - Result of examination as part of abdominal aortic aneurysm screening" """"""
  * resultDate 0..1 dateTime "A.3.4.5.1 - Date of USG examination result" """Date on which the patient underwent screening ultrasonography."""
  * examinationResult 0..1 CodeableConcept "A.3.4.5.2 - Ultrasound examination result" """Result of the screening ultrasound examination."""