Logical: LogCzRadiologyCz
Id: LogRadiologyCz
Title: "A.3.4 - Radiologie"
Description: """Sdílený zdravotní záznam - Screeningové vyšetření radiologem."""

* mamografickeVysetreni 0..1 Base "A.3.4.1 - Výsledek mamografického vyšetření v rámci screeningu karcinomu prsu" """"""
  * datumVysledku 0..1 dateTime "A.3.4.1.1 - Datum výsledku mamografického vyšetření" """Datum provedení mamografie."""
  * denzitaTkane 0..1 CodeableConcept "A.3.4.1.2 - Denzita prsní tkáně dle klasifikace BIRADS/ Tabár" """Denzita prsní tkáně pacientky."""
  * vysledekVysetreni 0..1 CodeableConcept "A.3.4.1.3 - Výsledek mamografie" """Výsledek mamografie."""
* vysledekBiopsiePrsu 0..1 Base "A.3.4.2 - Výsledek biopsie v rámci screeningu karcinomu prsu" """"""
  * datumVysledku 0..1 dateTime "A.3.4.2.1 - Datum výsledku biopsie" """Datum provedení biopsie."""
  * typBiopsie 0..1 CodeableConcept "A.3.4.2.2 - Typ biopsie" """Typ provedené biopsie."""
  * vysledekBiopsie 0..1 CodeableConcept "A.3.4.2.3 - Výsledek biopsie" """Výsledek provedené biopsie."""
* vysetreniPlic 0..1 Base "A.3.4.3 - Výsledek vyšetření v rámci časného záchytu karcinomu plic" """"""
  * datumVysledku 0..1 dateTime "A.3.4.3.1 - Datum výsledku provedeného LDCT" """Datum provedení LDCT"""
  * typVysetreni 0..1 CodeableConcept "A.3.4.3.2 - Typ LDCT vyšetření" """Pacientovi je prováděno vstupní vyšetření, kontrolní vyšetření v řádném termínu, nebo kontrolní po neurčitém výsledku."""
  * vysledekVysetreni 0..1 CodeableConcept "A.3.4.3.3 - Výsledek LDCT" """Výsledek screeningového LDCT."""
  * dpoporucenyPostup 0..1 CodeableConcept "A.3.4.3.4 - Výsledek vyšetření LDCT: Další doporučené vyšetření" """Závěrečné zhodnocení výsledků lékařem."""
* vysetreniProstaty 0..1 Base "A.3.4.4 - Výsledek vyšetření v rámci časného záchytu karcinomu prostaty" """"""
  * datumVysledku 0..1 dateTime "A.3.4.4.1 - Datum výsledku MRI" """Datum provedení MRI"""
  * typVysetreni 0..1 CodeableConcept "A.3.4.4.2 - Typ MRI vyšetření" """Pacientovi je prováděno MRI bez kontrastní látky, nebo MRI s kontrastní látkou."""
  * vysledekVysetreni 0..1 CodeableConcept "A.3.4.4.3 - Výsledek provedené MRI (PI-RADS)" """Výsledek provedené MRI dle systému PI-RADS (hodnotící skóre)."""
  * nalezPIRADS3 0..1 CodeableConcept "A.3.4.4.4 - Nález v případě PI-RADS 3" """Zóna nálezu v případě PI-RADS 3."""
* vysetreniAneurismatuAbnormalniAorty 0..1 Base "A.3.4.5 - Výsledek vyšetření v rámci screeningu aneurysmatu abdominální aorty" """"""
  * datumVysledku 0..1 dateTime "A.3.4.5.1 - Datum výsledku USG vyšetření" """Datum, kdy je pacientovi provedeno screeningové ultrasonografické vyšetření."""
  * vysledekVysetreni 0..1 CodeableConcept "A.3.4.5.2 - Výsledek USG vyšetření" """Výsledek screeningového ultrasonografického vyšetření."""
