Logical: LogCzUrologyCz
Id: LogUrologyCz
Title: "A.3.7 - Urolog"
Description: """Sdílený zdravotní záznam - Screeningové vyšetření urologem."""

* vysetreniKarcinomuProstaty 0..1 Base "A.3.7.1 - Výsledek vstupního PSA vyšetření v rámci časného záchytu karcinomu prostaty" """"""
  * datumVysledku 0..1 dateTime "A.3.7.1.1 - Datum výsledku screeningového PSA" """Datum, kdy je pacientovi proveden odběr screeningového PSA (vstupní PSA odběr v rámci screeningové epizody)."""
  * hladinaPSA 0..1 integer "A.3.7.1.2 - Hladina screeningového PSA" """Hodnota screeningového PSA v  UG/L (hodnota vstupního PSA odběru v rámci screeningové epizody)."""
* navazujiciUrologickeVysetreni 0..1 "A.3.7.2 - Výsledek navazujících urologického vyšetření  v rámci časného záchytu karcinomu prostaty" """"""
  * datumVysledku 0..1 dateTime "A.3.7.2.1 - Datum výsledku vyšetření" """Datum, kdy bylo provedeno vyšetření."""
  * vysledekVysetreni 0..1 CodeAbleConcept "A.3.7.2.2 - Výsledek klinického vyšetření" """Výsledek provedeného klinického vyšetření (per rectum a případná další vyšetření)."""
  * hladinaPSA 0..1 integer "A.3.7.2.3 - Hladina PSA" """Hodnota navazujícího PSA v  UG/L (hodnota PSA odběru)."""
  * objemProstaty 0..1 integer "A.3.7.2.4 - Objem prostaty" """Objem prostaty ze zobrazovacích vyšetření."""
  * PSADenzita 0..1 integer "A.3.7.2.5 - Určení PSA denzity (PSAD)" """PSA denzita."""
  * PSAVelocita 0..1 integer "A.3.7.2.6 - Určení PSA velocity (PSAV)" """PSA velocita (ng/ml/rok). PSAV se neprovádí v případě, když je k dispozici pouze jeden výsledek PSA."""
  * dalsiPostup 0..1 CodeAbleConcept "A.3.7.2.7 - Výsledek vyšetření: Další doporučené vyšetření" """Závěrečné zhodnocení výsledků lékařem."""
 * navazujiciBioptickeVysetreni 0..1 Base "A.3.7.3 - Výsledek navazujícího bioptického vyšetření  v rámci časného záchytu karcinomu prostaty" """"""
  * datumVysledku 0..1 dateTime "A.3.7.3.1 - Datum výsledku bioptického vyšetření" """Datum provedeného bioptického vyšetření prostaty na akreditovaném pracovišti."""
  * typBiopsie 0..1 CodeAbleConcept "A.3.7.3.2 - Typ provedené biopsie" """Typ provedené biopsie prostaty."""
  * vysledekVysetreni 0..1 CodeAbleConcept "A.3.7.3.3 - Výsledek bioptického vyšetření" """Výsledek bioptického vyšetření."""
