Logical: LogEnUrologyCz
Id: UrologyCz
Title: "A.3.7 - Urology"
Description: """Shared Health Record - Screening examination by urologist."""

* prostateCancerScreening 0..1 Base "A.3.7.1 - Result of initial PSA test as part of early detection of prostate cancer" """"""
  * resultDate 0..1 dateTime "A.3.7.1.1 - Date of PSA screening result" """Date on which the patient underwent PSA screening (initial PSA sampling as part of the screening episode)."""
  * PSALevel 0..1 integer "A.3.7.1.2 - Screening PSA level" """Screening PSA value in  UG/L (initial PSA test value as part of the screening episode)."""
* followupUrologicalExamination 0..1 Base "A.3.7.2 - Result of follow-up urological examinations as part of early detection of prostate cancer" """"""
  * resultDate 0..1 dateTime "A.3.7.2.1 - Date of examination result" """Date on which the examination was performed."""
  * examinationResult 0..1 CodeableConcept "A.3.7.2.2 - Result of clinical examination" """Result of the clinical examination performed (per rectum and any other examinations)."""
  * PSALevel 0..1 integer "A.3.7.2.3 - PSA level" """The value of the follow-up PSA in  UG/L (PSA sample value)."""
  * prostateVolume 0..1 integer "A.3.7.2.4 - Prostate volume" """Prostate volume from imaging examinations."""
  * PSADensity 0..1 integer "A.3.7.2.5 - Determination of PSA density (PSAD)" """PSA density."""
  * PSAVelocity 0..1 integer "A.3.7.2.6 - Determination of PSA velocity (PSAV)" """PSA velocity (ng/mL/year). PSAV is not performed if only one PSA result is available."""
  * furtherProcedure 0..1 CodeableConcept "A.3.7.2.7 - Examination result: Further recommended examinations" """Final evaluation of results by a physician."""
* followupBiopsy 0..1 Base "A.3.7.3 - Result of follow-up biopsy  as part of early detection of prostate cancer" """"""
  * resultDate 0..1 dateTime "A.3.7.3.1 - Date of biopsy examination result" """Date of prostate biopsy performed at an accredited facility."""
  * biopsyType 0..1 CodeableConcept "A.3.7.3.2 - Type of biopsy performed" """Type of prostate biopsy performed."""
  * examinationResult 0..1 CodeableConcept "A.3.7.3.3 - Biopsy examination result" """Result of the biopsy examination."""